#!/usr/bin/env python

import vector_upstart
import os


j = vector_upstart.Job(name="vector1-core", user='root', interface=os.environ.get('ROBOT_NETWORK'), master_uri=os.environ.get('ROS_MASTER_URI'), job_start_file='job-start-vector1.em')

# Stuff to launch on system startup.
j.add(package="vector1_bringup", filename="launch/vector1.launch")

j.install()


